### ISSUE TITLE
Babyagi + SingularGPT - Device automation ? [Must read]

### ISSUE THREAD

**Issue by abhiprojectz** [yoheinakajima/babyagi#105]
What if those autonomous bots can actually control your device like a human ?

Will it become Super Human ? 

[https://github.com/abhiprojectz/SingularGPT](https://github.com/abhiprojectz/SingularGPT)

SingularGPT - Can easily automate anything on what's your device and even headless?

It can even detect and recognise elements using by its own. 

**No crawling system no restriction.**

![](https://user-images.githubusercontent.com/64596494/230727123-b01d6607-9f08-4abe-ae00-bda1eacbc5bf.PNG)

It can perform UI actions and can internally process them and also automates them all by natural language.

Anyone please leave your thoughts!

**Comment by p21nc3** [comment]
SingularGPT is pretty astounding in its capacity to simply automate anything on a screen, identify elements using its own processes, and carry out UI operations using natural language. 

It could be categorized as a "superhuman" tool due to its unconstrained abilities. 

But there is reason to be concerned about the possibility of abuse or unforeseen consequences.

**Comment by abhiprojectz** [comment]
@p21nc3  Exactlty, i'm also aware of this concern, but the goal behind OpenSourcing it was to focus on its positive side.

Imagine how it could help when used only focusing on positive side.
