### ISSUE TITLE
Enhancement suggestion: Self-improvement 

### ISSUE THREAD

**Issue by MatShep** [yoheinakajima/babyagi#19]
Enhancement suggestion: add capability of evaluating, testing and updating babyAGIs own code.

**Comment by bigchain** [comment]
Here are a few suggestions to improve the script:


Error handling: Add error handling to various parts of the script, such as API calls and user inputs. This can help make the script more robust and easier to debug.



Logging: Implement logging to keep track of the script’s progress, errors, and any other useful information. This can help with troubleshooting and understanding the script’s behavior.



User input: Allow users to input tasks or modify the objective during runtime, making the script more interactive and adaptable to changing requirements.



Concurrency: Introduce concurrency or parallelism to execute multiple tasks simultaneously, which could speed up the overall process.



Configurable parameters: Make more parameters configurable (e.g., the number of tasks to retrieve, the context, and the engines used), enabling users to fine-tune the script to their needs.



Customizable functions: Allow users to define custom task creation, prioritization, and execution strategies, making the script more versatile and suitable for different use cases.



Performance metrics: Incorporate performance metrics to evaluate the effectiveness of the AI system. This can help users understand the progress made towards the ultimate objective.



Persistent storage: Instead of using an in-memory task list, use a persistent storage solution (e.g., a database) to store tasks, results, and other relevant data. This would enable the script to resume from its previous state in case of failure or interruption.



End conditions: Define specific end conditions that signal the completion of the overall objective, stopping the script automatically once the conditions are met.

**Comment by DDanlov** [comment]
Use the python time package to stop the running after a certain amount of time specified in the config.
