### ISSUE TITLE
Task decomposition (one task to many tasks)

### ISSUE THREAD

**Issue by drusepth** [yoheinakajima/babyagi#56]
The loop of

1. Create tasks
2. Prioritize tasks
3. Execute next task

seems to work well, but one point of contention crops up when analyzing the scope and complexity of individual tasks. For example, a task of "install ruby 3.2.1" seems completable within a single chain of ops, but a larger task of "start a company" would probably be better executed after breaking it up into smaller, more discrete steps ("search competitors for a desired name", "register a company", "publish a landing page", etc) without then tracking the task as complete.

Is there any work planned or being done in analyzing scope/complexity of tasks and decomposing one task into many, especially in place of "executing" that larger task? Seems like something that would be useful for larger, more involved goals attempting to complete more complicated tasks.

**Comment by DDanlov** [comment]
A clear solution would be to decide if the task needs to be managed in several sub-tasks or not. This would be done simply by modifying the prompt which would tell GPT first to decide if the task is complex or not and then to divide it into subtasks only if necessary. I think that if he manages to explain concepts in a simple, intermediate and complex way (e.g explain it to me as if I were 5 years old), it is because he knows how to distinguish a simple task from a complex task. If after testing it doesn't work too well, we could include examples and perform the prompt in few shot learning.

**Comment by siddiqss** [comment]
It's unstoppable. Even simpler tasks are further divided into sub-tasks. I tried asking "how to install python on mac", it could be done in few steps but it continued going deeper into installing packages and stuff. Somehow it needs to know where it needs to be stopped.

**Comment by DDanlov** [comment]
Yes, it definitely needs. The answer may be in the formulation, it might exist a clever prompt which makes it converge towards the desired results.
