### ISSUE TITLE
Issue: Task list numbering gets messed up.

### ISSUE THREAD

**Issue by kyleshrader** [yoheinakajima/babyagi#76]
Currently the numbering of the task list gets messed up quite often.

A potential fix would be to track the numbering separate from the description.

![image](https://user-images.githubusercontent.com/5632571/230682069-4e0168c8-b78a-4832-8c0e-7e1b1972f24b.png)

Notice the numbering continues to reset.

Or get misordered:

![image](https://user-images.githubusercontent.com/5632571/230682154-d8635faa-71a9-41be-9149-eda3c8454fb1.png)

**Comment by francip** [comment]
The issue is that the ordering is used to do the task prioritization, not to track the actual order of the task generation.
Might be better to have two separate numbers - one absolute (this is the n-th task generated) and one relative (this is the k-th task in the list at this iteration)
Absolute then can be also used to link parent-child tasks, so we can do cool graphs and track the chain of execution.

**Comment by kyleshrader** [comment]
I like the idea of separating id and priority. In my concept repo #80 I made an id that gets updated by prioritizer. But maybe that should be the priority and then id doesn't update.
