### ISSUE TITLE
consider using sqlite + hnsqlib for embedding search/storage

### ISSUE THREAD

**Issue by wskish** [yoheinakajima/babyagi#8]
very cool concept here.

For similar types of projects I have found using sqlite database + hnswlib useful since with pinecone I still typically need another database anyway for persisting other state.  

I have a minimal integration of these 2 that behaves similar to pinecone: 
https://github.com/jiggy-ai/hnsqlite

Here i have babyagi working with hnsqlite 0.2.0:
https://github.com/wskish/babyagi/blob/hnsqlite-integration/babyagi.py

Let me know if this approach is of any interest.   It seems like a possible next step is persisting the task_list so the sqlite db could be useful for that.

**Comment by StableInquest** [comment]
So it you were to combine this method with with LLAMA you could go 100% local?

**Comment by swittk** [comment]
@StableInquest  I think so; however it seems LLaMA models tend to ramble stuff that causes the task list format to go wrong.
I implemented @wskish 's changes here https://github.com/swittk/babyagi/tree/alllocal while also using LLaMA.cpp embeddings and the babyagi script often fails with the error at the line `this_task_id = int(task["task_id"])`, because the task string, instead of being `${number}. ${result_text_here}`, ends up being some garbage like `"Solve world hunger is not a task description, it's an ultimate objective of your team."` so it simply crashes since that's obviously not an int lol. You'd need a rather good model to use too I guess.

**Comment by francip** [comment]
There are few folks looking at replacing Pinecone with different local vector DB (Weaviate, Chroma, FAISS, etc.) If you are interested in joining the Discord and helping them figure out the best way, let me know.

**Comment by eren23** [comment]
> There are few folks looking at replacing Pinecone with different local vector DB (Weaviate, Chroma, FAISS, etc.) If you are interested in joining the Discord and helping them figure out the best way, let me know.

Hello, I'll also fork the project to see what can I replace with the open source alternatives, in https://github.com/geeks-of-data/knowledge-gpt we mainly use huggingface sentence transformers for embedding extraction ( ada is supported ) and for vector storage, we support SVM, IP distance, faiss and chroma. What I can try is to add an alternative for embedding extraction and for vector storages. About the question answering model, I'm in the favor of keeping openai models as the main for now as the opensource alternatives are not as good and is also resource intensive to run. If I make any meaningful progress I'll open a draft PR and visit the dc channel to let you guys know.

Thanks a lot for the project.

**Comment by francip** [comment]
I just merged two changes - #186 and #218 which add ChromaDB as a default results store and Pinecone as an extension which is automatically triggered for all current Pinecone users.

If there is still interest in sqlite + hnsqlib, you can open new issue or directly create a PR that adds it as an extension similar to how Pinecone is implemented.
