### ISSUE TITLE
Pinecone Pods

### ISSUE THREAD

**Issue by cometbus** [yoheinakajima/babyagi#95]
HTTP response body: The index exceeds the project quota of 1 pods by 1 pods. Upgrade your account or change the project settings to increase the quota.

do I need a standard $70 a month pinecone account to use this?

**Comment by gdj0nes** [comment]
Hi @cometbus you shouldn't need to upgrade, a single pod holds close to a million vectors. It's possible that a previous run of the script did not run close out well. Check the pinecone console or use the SDK to remove any running indexes.

**Comment by aliasfoxkde** [comment]
I'm having the same issue and it's a brand new Index and API key. Not sure what I'm doing wrong, but I'm not particularly familiar with Pinecone (have only used the API with a few repos thus far). Error: "HTTP response body: The index exceeds the project quota of 1 pods by 1 pods. Upgrade your account or change the project settings to increase the quota."

**Comment by aliasfoxkde** [comment]
I misunderstood this step and created the index myself (from the Pinecone website). Realizing my mistake and just providing the API Key and ENV, the "babyagi.py" file generated the index (this is where it was failing because it was trying to "create" a new instance but one on a free tier already exist). I confirmed everything works now. My mistake, but I would suggest adding a troubleshooting bit to the main README.md file. In either case, people can find this with a quick search, so this issue can be closed.

**Comment by benrodrigue** [comment]
I had the same issue. Created an Index thinking I was connecting to it. Thank goodness for this thread.

**Comment by GSCrawley** [comment]
aliasfoxkde,  what did you do to fix the issue? you weren't very clear.

**Comment by aliasfoxkde** [comment]
I had "accidently" created an index/DB through the Pinecone website, thinking that was right. This is incorrect. Simply register the API through Pinecone and add it to your ENV file. Babyagi.py will do the rest (automatically create the index/DB). Hope that clarifies.

**Comment by mertdeveci5** [comment]
I am experiencing the same issue though this is not related to BabyAGI. I delete the index and run my notebook however I still get the same error

**Comment by eescobosa** [comment]
does somebody know if the standard plan charge 70 usd per pod or is only that charge? I read something about you have the limit of 5 pods in that plan, and each index has to use one.
